#!/bin/bash

at="apktool"
gr="grep"
read -p " {sl0p} Please Enter The Name Of The Apk: " apk
echo " {sl0p} We Gonna Extract The $apk"
sleep 2
$at d $apk
read -p " {sl0p} Please Enter The Name Of The folder: " afl
locate $afl
read -p " {sl0p} Please Enter The Search String: " sst
$gr -nr "$sst" $afl
