#!/bin/bash

at="apktool"
gr="grep"
grs="grep -nr "token" catchv1.0"
read -p " {sl0p} Please Enter The Name Of The Apk: " apk
echo " {sl0p} We Gonna Extract The $apk"
sleep 2
$at d $apk
read -p " {sl0p} Please Enter The Name Of The folder: " afl
locate $afl
$gr -nr "$grs" $afl
